### ISSUE TITLE
SSH key in browser

### ISSUE THREAD

**Issue by patatetom** [butlerx/wetty#182]
hello,

is there a way to use the SSH (private) key directly from the browser to avoid the authentication phase (password) ?

`[ browser ] <--lan--> [ nginx (https) | wetty | sshd ]`

regards, lacsaP.

**Comment by antonyjim** [comment]
EDIT: See [Issue #178](https://github.com/krishnasrinivas/wetty/issues/182). I'm still leaving this due to some other potentially useful information.

I'm not sure if you are looking for an implementation like `${serverAddress}/wetty?key=` or something similar, but there is no way for the browser to have it's own private key store due to the fact that the browser itself is not actually hosting the SSH agent. The only thing the browser is doing is displaying text on the screen. **All** of the logic behind the terminal is done on the wetty host.

If you are using one host running as a proxy to another host, then you can simply set up public key authentication between the wetty host and the target server using `ssh-keygen`.  Though if this is the case, then it is out of the scope of this wetty.

On a side note, I have considered forking wetty to integrate this into my web application by storing the ssh keys and linux usernames in a database alongside the user registration information. Then when a user is logged in to the application, my application will simply load an ssh wrapper that will auto-fetch the keys and username, then establish a localhost ssh session using said keys. However, this is completely out of the scope of this repo as well and would require another user to process the initial session establishment... However, the user still logs into the normal application with their application credentials. Just a suggestion into how you could potentially implement what you are suggesting.

**Comment by patatetom** [comment]
thank you for your explanations.
my goal was to replace putty with a web interface while maintaining key authentication...
good work otherwise.

regards, lacsaP.
