### ISSUE TITLE
hanging ssh sessions.

### ISSUE THREAD

**Issue by plato79** [butlerx/wetty#19]
Hi,

I am using wetty via nginx to connect to my NAS server.. 
I assigned its' own domain name ( tty.domain.com instead of domain.com/wetty ) and using SSL security with nginx web server..

While it works perfectly, after a few runs I saw a lot of hanging tcsh and ssh sessions in task list. What could be the cause? I didn't saw any problems but after a while it would be a big problem..

**Comment by butlerx** [comment]
Yeah this is a problem ive noticed and run in to, if the user closes the tab without closing the shell the ssh connection will stay open because closing a tab doesn't kill the term, this may have been fixed in #18 but i haven't had a chance to test it yet.

**Comment by nosemeocurrenada** [comment]
Just tested it, it wasn't fixed. Fixed it adding a `term.destroy();` line just after the term.end (); in wetty.js:72
So now my 'disconnect' handler looks like this
```
    socket.on('disconnect', () => {
      term.end();
      term.destroy();
      events.emit('disconnect');
    });
```

It wasn't closing because term.end calls the net.Socket.end() function which does not close the socket
([https://nodejs.org/api/net.html#net_socket_end_data_encoding]())
I don't know if this behavior was intended by the pty.js developers

**Comment by butlerx** [comment]
i think that using `term.kill()` might be better then `term.destroy()`

```
    socket.on('disconnect', () => {
      term.kill();
      term.end();
      events.emit('disconnect');
    });
```

**Comment by nosemeocurrenada** [comment]
`term.destroy()` calls `term.kill()`
[https://github.com/chjj/pty.js/blob/master/lib/pty.js#L357](https://github.com/chjj/pty.js/blob/master/lib/pty.js#L357)

**Comment by butlerx** [comment]
ah yes i missed that

**Comment by butlerx** [comment]
thanks for doing the research @nosemeocurrenada thats been added now
