### ISSUE TITLE
Potential to miss file download sequences

### ISSUE THREAD

**Issue by benletchford** [butlerx/wetty#214]
**Potential to miss file download sequences**

From @kb1ooo
> I think that there might be another potential point of failure. Since the escape sequences are multi-character, isn't there a possibility that they (more likely FILE_END if it's going to happen) can get split across data buffers? In that case, the current implementation would appear to miss the marker because it's expecting it to be contiguous in the data buffer. I.e. data.indexOf(FILE_END) would never return anything but -1. I know next to nothing about terminals (nor about javascript) so I could be totally wrong, maybe you are guaranteed that those sequences are contiguous?

We need to look into how we can guarantee we won't miss the `FILE_BEGIN` or `FILE_END` sequence of characters if they're split up over multiple `data` calls.

Thanks to @kb1ooo for pointing this out! :D

I'd also like to point out the likelihood of something like this happening is probably quite low - at the very least worth discussing :)

**Comment by benletchford** [comment]
@butlerx, I'm happy for you to assign this to me :)

**Comment by kb1ooo** [comment]
@benletchford I've been working on a fix for this, mostly because I made a change to accommodate the gnu screen issue and figured I'd work on this as well.    As I got into it, I realized that there are actually a few more corner case (and not so corner case issues).   

1.  Data in the buffer, but outside the begin/end delimiters, is lost (i.e. not written to the terminal).  
2.  A FILE_BEGIN sequence that occurs after a FILE_BEGIN but before a FILE_END is not handled properly.  Or similarly a FILE_END that occurs before a FILE_BEGIN has occurred is not ignored.
3.  There may be multiple segments that occur within a single buffer and that is not handled.  

I've fixed these 3 issues.  But the original problem (a marker may be split across multiple buffers) is a bit tricky to get right.  Let me know if you've started on this or how far you've gotten.

**Comment by kb1ooo** [comment]
@benletchford oops I missed your fix.  I will take a look.

**Comment by kb1ooo** [comment]
Appreciate the fix @benletchford, pushed version working well on my end.  To work around my gnu screen issue (if you recall I mentioned before that gnu screen buffers with multiple beg/end sequences) I added a character (that doesn't have a base64 collision) to the begin end sequences that wetty is looking for and then remove all the extra begin/end sequences from the buffer in the `onCompleteFileCallback`.  So in `src/client/download.ts`
```
-const DEFAULT_FILE_BEGIN = '\u001b[5i';
-const DEFAULT_FILE_END = '\u001b[4i';
+const DEFAULT_FILE_BEGIN = '\u001b[5i[';
+const DEFAULT_FILE_END = ']\u001b[4i';
```

And then in `src/client/index.ts`
```
   const fileDownloader = new FileDownloader((bufferCharacters: string) => {
     let fileCharacters = bufferCharacters;
+    const FILE_BEGIN_SEG = '\u001b[5i';
+    const FILE_END_SEG = '\u001b[4i';
+
+    fileCharacters = fileCharacters.split(FILE_BEGIN_SEG).join('');
+    fileCharacters = fileCharacters.split(FILE_END_SEG).join('');
``` 
Just changes adding a character to the sequences in the script to initiate the download.  Actually, I have a suggestion in the example script to use octal codes instead of embedding the escapes because if you cat the script it will initiate a download.   I post a separate issue. 

Thanks,
kb1ooo
