### ISSUE TITLE
Connecting to Multiple Remote Host With One Wetty Instance

### ISSUE THREAD

**Issue by aksh7860** [butlerx/wetty#222]
Hi,

I have a use case, I need to connect wetty with multiple remote hosts. One way of doing this would be to run multiple instances of wetty and connect each with the dedicated hosts.
However, I was wondering can I connect with multiple hosts with a single instance of wetty running.

Something like this:
http://yourserver:3000/wetty/ssh/username?pass=password
With Above URL I can connect with multiple users on the same wetty instance, can I do the same with different hosts.

**Comment by ntorga** [comment]
Not sure if it's what you looking for exactly, but since v1 you can use the ?host query string, for example: "http://yourserver:3000/wetty/ssh/username?host=yourserver.com".

Once you use the ?host param, Wetty will ignore the "username", so you want to use "?host=youruser@yourserver.com" if you need multiple users on multiple hosts.

**Comment by aksh7860** [comment]
Hi ntroga,

Thanks for the help, this is what i was looking for.

**Comment by lakshman-arrcus** [comment]
Hi @ntorga, I am trying to do the same thing here but I do not see this connect to the new host parameter specified. Was support removed for this option?

**Comment by projectchalkboard** [comment]
@lakshman-arrcus same issue. I just installed latest docker and cannot pass the host perimeter in the URL
