### ISSUE TITLE
Pasting text via ctrl-shift-v also overlays pasted text onto first line in black

### ISSUE THREAD

**Issue by kb1ooo** [butlerx/wetty#238]
**Describe the bug**
Sometimes, window gets into a state such that when pasting text from clipboard via ctrl-shift-v, the text gets pasted as it should at the cursor, but it also gets overlaid on the first line of the terminal in black.  Only happens via ctrl-shift-v, doesn't happen with right click->paste. 

**To Reproduce**
Steps to reproduce the behavior.  
Again, this only happens sometimes and I'm not sure how to get it into this state.  Once it starts happening, it will always happen for the window, even if I refresh the wetty page and re-login.
1. Highlight some text and copy into the buffer via right click->copy
2. Paste at the cursor via ctrl-shift-v
3. Highlight the top line of the terminal to reveal the pasted characters in black.

**Expected behavior**
No overlay on top line

**Desktop (please complete the following information):**
 - OS:  Desktop: OS Windows 10, Terminal:  Ubuntu 16.04 or 18.04
 - Browser: firefox 68.5.0esr 64bit
 - Version: a97c4ee

**Comment by kb1ooo** [comment]
Do others not experience this?

**Comment by frepke** [comment]
> 
> 
> Do others not experience this?

Yes, same problem for me :(
But it looks a Firefox thing

**Comment by logicsys** [comment]
I'm also still experiencing this with firefox, I have tried 2.6.0 & 2.5.0.
I'll see if i can resolve it myself, I'll make a pull request if I get anywhere :D

**Comment by foodelevator** [comment]
I was able to "solve" it by upgrading from Firefox 102 to 115.

The issue seems however to be that pasted text gets prepended to the div with the class `xterm-helpers`, which seems to be managed by [xterm.js](https://github.com/xtermjs/xterm.js). A fix might be to make the text in there invisible with something like `document.querySelector(".xterm-helpers").style.color = '#0000'`.

However, when upgrading my browser version, the text doesn't appear there at all so just making it invisible would be more of a workaround than a solution.
