### ISSUE TITLE
Maintenance and Diff

### ISSUE THREAD

**Issue by E3V3A** [butlerx/wetty#31]
Hi! 
Thanks for keeping this updated and trying to maintain. 
What is the current plan and status of this? How does it differ from [the original](https://github.com/krishnasrinivas/wetty) at this moment?

**Comment by butlerx** [comment]
no problem. 

this fork has most of its changes based on the front end trying to make hterm work better for people such as rendering errors and browser support.
its also had the server changed to try and make it more modular so it can be a package and well as a binary. 
there's also additional work done on making it easier to run from docker and other OSes. 
An ssh wrapper that prompts for login rather than a default login.

im currently looking at [removing hterm and the ssh wrapper](https://github.com/butlerx/wetty/pull/29) to give more os and browser compatibility.
