### ISSUE TITLE
Windows 10 - IE11 Issue

### ISSUE THREAD

**Issue by ccjoelm** [butlerx/wetty#321]
**Describe the bug**
We are looking at using WeTTy, but unfortunately have a requirement to use IE 11 on Windows 10.  When we try to load in Windows 10 / IE 11 it doesn't work, but we don't get any errors.  I've tried a couple of other xtermjs based terminal apps like WebSSH & WebSSH2 and they work in IE11 & Edge, but I'd prefer to use WeTTy. 

**To Reproduce**
1. Run WeTTY as docker container:  docker run -p 3000:3000 -i -t --rm wettyoss/wetty --ssh-host=<host>
2. Start IE 11 or Edge and go to http://localhost:3000/wetty/ssh/jmorris
3. The terminal doesn't load, but I don't see any errors in the console either

**Expected behavior**
I tested on Chrome, Firefox, and Edge on the same Windows 10 computer and it worked there.

**Screenshots**
![wetty_ie11](https://user-images.githubusercontent.com/22804192/106299376-b1683380-621a-11eb-8714-ed2e29fee8fa.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: IE 11
 - Version: IE 11 1909

I still had the old Edge installed on my computer and it didn't work with the old Edge that shipped with Windows 10.  I installed the new Edge browser and it worked fine with it.

**Comment by butlerx** [comment]
this is likely due to wetty using web modules, which I don't believe are supported in IE. 
Web modules were switched to in v2 to try all for faster rendering. 
v1.4.1 should support ie 11 it is stable but is missing some fixes for saml support( If these are needed ill see if it is possible to backport them).
The documentation is majority the same aside from some command flags and lack of support for a config file.
