### ISSUE TITLE
bash: -p: command not found

### ISSUE THREAD

**Issue by longyearbyen91** [butlerx/wetty#326]
On debian buster
No issue during setup with atoz documentation
When conneting to web interface  I've got a "bash: -p: command not found" after entering password.

Error Message is :
myuser@localhost's password: 
bash: -p: command not found
Connection to localhost closed

No issue with same user with ssh connection with putty

**Comment by longyearbyen91** [comment]
I confirm same issue than [https://github.com/butlerx/wetty/issues/320](https://github.com/butlerx/wetty/issues/320)

It works correctly with version 2.0.2
Replace
yarn global add wetty --prefix ~/
with
yarn global add wetty@2.0.2 --prefix ~/

**Comment by infinitewiz** [comment]
The issue does not occur when running as root since it uses login instead of ssh.
I did run wetty as root and forced the use of ssh and observed the same error.

**Comment by micahnz** [comment]
I have the same issue, also 2.02 does not work for me because I have 2FA turned on for SSH and I am not prompted for the 2FA code, 2.0.3 correctly prompts me for this over SSH but I get the command not found.

I can run either version as root however and it works as expected.

**Comment by infinitewiz** [comment]
I ran wetty standalone from the shell and used strace to record the process related system calls.
This is from 2.02:

3255  execve("/usr/bin/ssh", ["ssh", "marc@127.0.0.1", "-t", "-p", "22", "-o", "PreferredAuthentications=passwor"..., "-o", "UserKnownHostsFile=/home/marc/.s"..., "-o", "StrictHostKeyChecking=yes"], 0x7ffe4bcca950 /* 28 vars */) = 0

This is from 2.03:

2291  execve("/usr/bin/ssh", ["ssh", "marc@127.0.0.1", "-t", **"", "",** "-p", "22", "-o", "PreferredAuthentications=passwor"..., "-o", "UserKnownHostsFile=/home/marc/.s"..., "-o", "StrictHostKeyChecking=yes"], 0x7ffca93a3530 /* 28 vars */) = 0

I then just ran each ssh invocation from a shell to confirm what I was seeing in the strace output.  The issue is the two empty strings after the **_"-t"_** argument to ssh.  When those two empty strings are present I get the same error message that is reported in the bug: **_bash: -p: command not found_**

**Comment by infinitewiz** [comment]
I don't know JavaScript but I believe I found the issue and have a workaround so 2.03 can be used.
The issue appears to be the addition of the **--user-config** option where one can specify an optional ssh config file.

It appears that when one does not specify **--user-config _ssh_config_file_** that is when we observe the two empty strings when ssh is invoked.

I invoked wetty from the shell to test this and added **--ssh-config /etc/ssh/ssh_config** and I was able to successfully login.
I made the same changes to my wetty.service file since I am using systemd to start wetty and everything appears to be working fine.

@butlerx hope this helps you with fixing the issue.

**Comment by denppa** [comment]
Yeah the previous version does fix this issue. Will this bug be fixed in the next release?

**Comment by butlerx** [comment]
can users verify if the issue persists in version `2.1`

duplicate of #308

**Comment by Salamandar** [comment]
Well it looks like the issue is solved for me in 2.1.1. Thanks !

**Comment by butlerx** [comment]
great to hear
