### ISSUE TITLE
Docker Hub image not updated

### ISSUE THREAD

**Issue by ameinild** [butlerx/wetty#366]
Hello

Would you consider putting an updated Docker image on Docker Hub? It seems neither https://hub.docker.com/r/wettyoss/wetty or https://hub.docker.com/r/butlerx/wetty has the latest version.

Thanks.

**Comment by frederik-b** [comment]
Just notice the same thing.
It's the only tool I can find which wasn't abandoned only to find out, that the dockerhub images indeed are abandoned.

**Comment by butlerx** [comment]
This is because docker hub has begun limiting free auto builds ill likely need to add a gh action to auto build and push an image 

According to docker hub automated builds are only  "Available with Pro, Team and Business subscriptions."


https://github.com/marketplace/actions/build-and-push-docker-images for automation

**Comment by butlerx** [comment]
Alright, we are now building and publishing images for dockerhub and ghcr on each commit to main
