### ISSUE TITLE
security risks http

### ISSUE THREAD

**Issue by coderofsalvation** [butlerx/wetty#50]
I know https is a nobrainer when it comes to security.
But how likely is it that somewhere somebody is sniffing http websocketpackets for passwords, of a http wetty session running in a docker on some server.

**Comment by brlin-tw** [comment]
I suspect there's also security risks on HTTPS, which hackers can exploit the web interface to brute-force attack on user's password.

**Comment by TotallyInformation** [comment]
NEVER use http for anything other than a totally open, public information server. Yes, something (rather than someone) will start sniffing.

HTTPS risks are main about having poor certificate chain checking. Harder to achieve but possible, especially in unreliable wi-fi environments such as coffee shops.

**Comment by butlerx** [comment]
using http on the open web should always be considered unsecured. and leaking access and passwords a possibility
