### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by 7r4s3r** [butlerx/wetty#82]
npm install missing. will not install

**Comment by seancallaway** [comment]
I just ran this today. What exactly did you run and what output was received?

**Comment by 7r4s3r** [comment]
The npm file is missing and  i can't install it

**Comment by seancallaway** [comment]
That is definitely invalid syntax and doesn't sound like output from a program.

When you run `$ sudo npm install`, what does the console spit back?

**Comment by the-ashh** [comment]
So, I *think* I have the same problem as this guy, but I have the output

root@yep:~/wetty# sudo npm install

> pty.js@0.3.1 install /root/wetty/node_modules/pty.js
> node-gyp rebuild

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/wetty/node_modules/pty.js
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.1 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root/wetty
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/wetty/npm-debug.log
npm ERR! not ok code 0

**Comment by the-ashh** [comment]
Actually, I just fixed it! You have to do npm install node-gyp, then npm install pty.js
