### ISSUE TITLE
Nginx reverse proxy: different 'location'

### ISSUE THREAD

**Issue by kocane** [butlerx/wetty#92]
Hello.

What must I do in order to use another location for my nginx proxy? I can only get it to work with /wetty, i.e. https://domain.xyz/wetty. For instance, I wanna use /ssh or something... I've tried some different nginx settings but always end out with "cannot get /ssh"

Any help appreciated, thanks.

**Comment by pywhy** [comment]
Maybe rename the folder /wetty to /ssh and put /ssh in your nginx conf file.

**Comment by iz8mbw** [comment]
Hi.
I also need that. I was able to use another location (example /ssh) with a rewrite but in that way I can access both on /wetty and /ssh. I think that it's NOT ok because you, as me, want to use only /ssh instead of /wetty

**Comment by hvindin** [comment]
This is achievable using the ngx_http_subs_filter module. (I'm sure googling around a bit will point you in the right direction pretty quickly.) Even with an nginx-plus instance the module is packaged into the repositories so it's a fairly well used module.

I just tried @iz8mbw's use case of replacing /wetty with /ssh and it seems to work fine with the following configuration:

```
server {
  listen                 111.111.111.111:443 ssl http2;
  server_name            example.com;
  root                   /usr/share/nginx/html;
  location /ssh/ {
    subs_filter_types text/html application/javascript;
    subs_filter "/wetty/wetty.min.js" "/ssh/wetty.min.js";
    subs_filter "/wetty/socket.io" "/ssh/socket.io";
    proxy_redirect /wetty/ /ssh/;
    proxy_set_header Referer "$http_referer/wetty";
    proxy_pass http://127.0.0.1:3000/wetty/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $http_host;
    proxy_set_header X-NginX-Proxy true;
    proxy_read_timeout 43200000;
  }
}
```

The important bits are:

- `subs_filter_types text/html application/javascript;` - By default application/javascript won't be rewritten so you need to include this.

- both the `subs_filter` directives. I tend to get pretty specific with my directives, but that's probably about as loose as you can leave them if you don't want to potentially see unwanted behaviour.

- `proxy_redirect /wetty/ /ssh/;` is important as the node code running behind the nginx is expecting /wetty and will return responses that assume you have used /wetty. This seems to be related to if you are running the wetty service as root or not (I am running it as root so am using /bin/login not ssh for the connection.)

- `proxy_set_header Referer "$http_referer/wetty";` some of the code seems to look for the referer header and determine if wetty is in it or not. I just hacked over this by appending it to the end of whatever the incoming referer header is. Not sure how stable this is but it seems to work for me.

- `location /ssh/ {` and `proxy_pass http://127.0.0.1:3000/wetty/;` the trailing slashes are important to make sure that nginx doesn't just append the /ssh onto the /wetty.

The output ended up looking something like this, which seems to be what you're after:  
![example-uri](https://gist.githubusercontent.com/hvindin/87279d0b0f9437fbbf0d12c2fa3ce71c/raw/1b0f85bc12600a2a97478f8dbd6a14b875cb6582/example-ssh-wetty.png)

**Comment by iz8mbw** [comment]
Hi hvindin and thanks for your support!
I'm sorry but "/ssh" does not work on my side with that configuration, or better it works BUT I must leave also "/wetty" configured (proxied) in nginx.

So:
If "/wetty" is already proxied on nginx (to the http server on port 3000), in your way also "/ssh" will works.
But If I delete the reverse proxy part about  "/wetty" I was not able to access to "/ssh/ because the GET are answered with HTTP 404 not found...

/wetty/hterm_all.js -> HTTP 404
/wetty/socket.io/socket.io.js -> HTTP 404
/wetty/wetty.js -> HTTP404

My goal is to have another location (example "/ssh") that will go on "http://127.0.0.1:3000/wetty/" and "/wetty" must not be accessible and not directly proxied.

**Comment by iz8mbw** [comment]
OK, I found the issue.
The correct "subs_filter" part of your nginx config should be:

```
subs_filter "/wetty/hterm_all.js" "/ssh/hterm_all.js";
subs_filter "/wetty/socket.io" "/ssh/socket.io";
subs_filter "/wetty/wetty.js" "/ssh/wetty.js";
```

In this way it works, many thanks!

I want also remember that the module "nginx_substitutions_filter" is not inside nginx, so it's needed to build nginx from source and inlcude it. More info on: https://github.com/yaoweibin/ngx_http_substitutions_filter_module and on https://www.nginx.com/resources/wiki/modules/substitutions/
 

Many thanks!!
 On my side this issue can be closed.

**Comment by hvindin** [comment]
Odd, I happened to be connected to a machine with nginx+ at the time and didn't realise that the subs filter module isn't available from the non-plus repositories.

But that being said, you shouldn't need to include the module in an nginx rebuild from source, ever since dynamic modules you should be able to just build the module and copy it into the module directory before using it.

I've just tested this on a centos box with nginx OSS 1.13.8 installed using the following module compiled dynamically and it works ok:
https://gist.github.com/hvindin/2d1daf70ce2a5acfd92ca1f23a788d8e

Sorry I didn't realise that the subs module isn't an available default for nginx OSS, but glad to have been able to help.

**Comment by butlerx** [comment]
usign the flag `--base` you can change the path from `/wetty` to `/ssh`

**Comment by bahamut657** [comment]
Hi all.
I'm experiencing issues trying to reach wetty under Nginx using rewrite rules.
How to manage rewrite? It seems that using the --base flag is not helping.

For example:
If I load the Nginx endpoint https://abc.xyz/my/custom/path (that Is rewrited to localhost:3000/wetty), it seems to resolve correctly the root page but all resources fail to load(stylesheet, socket.io connection etc...), because they are pointing to /wetty/ path.
Is there a way to manage this case?
Best regards and very very good work!
